services:
  web:
    build:
      context: ./ziin-web
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      LOCAL_DB_PATH: /shared-data/local.db
    volumes:
      - ./data:/shared-data
    ports:
      - "6001:3000"
    restart: unless-stopped

  bot:
    build:
      context: ./ziin-bot
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      LOCAL_DB_PATH: /shared-data/local.db
    volumes:
      - ./data:/shared-data
    restart: unless-stopped

  inori:
    build:
      context: ./inori
      dockerfile: Dockerfile
    env_file:
      - ./inori/.env
    volumes:
      - ./inori/data:/app/data
    restart: unless-stopped
