client_config_backend: settings
client_config:
  client_id: 335895449067-94umigfsa6jo89eg1352uaaaruvd2tjv.apps.googleusercontent.com
  client_secret: ZVtkdZOuchBIzi9oubor9Uve

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install